services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - PUID=1000
        - PGID=1000
    container_name: bastion_cms_2_1-app
    restart: unless-stopped
    working_dir: /var/www
    user: "1000:1000"
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - bastion_cms_2_1
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: bastion_cms_2_1-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - bastion_cms_2_1
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: bastion_cms_2_1-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - bastion_cms_2_1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bastion_cms_2_1-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - bastion_cms_2_1
    depends_on:
      - mysql

  node:
    image: node:23-alpine
    container_name: bastion_cms_2_1-node
    restart: unless-stopped
    working_dir: /var/www
    user: "1000:1000"
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
      - "5174:5174"
    networks:
      - bastion_cms_2_1
    environment:
      CHOKIDAR_USEPOLLING: 1
      WATCHPACK_POLLING: true
    command: sh -c "npm install && npm run dev:all -- --host 0.0.0.0"

  redis:
    image: redis:7.4.3-alpine
    container_name: bastion_cms_2_1-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - bastion_cms_2_1

networks:
  bastion_cms_2_1:
    driver: bridge

volumes:
  mysql_data:
    driver: local
